import { 
  CitizenRequest, 
  Permit, 
  Payment, 
  Project, 
  Task, 
  Employee, 
  Attendance, 
  Leave, 
  Event, 
  Notification 
} from '@/types';

export const mockRequests: CitizenRequest[] = [
  {
    id: 'REQ001',
    citizen_id: 'CIT001',
    type: 'residency',
    status: 'pending',
    submission_date: '2024-01-15',
    description: 'Request for residency certificate',
    citizenName: 'John Smith',
  },
  {
    id: 'REQ002',
    citizen_id: 'CIT002',
    type: 'birth',
    status: 'in_review',
    submission_date: '2024-01-14',
    description: 'Birth certificate for newborn',
    citizenName: 'Sarah Johnson',
    assignedTo: 'Clerk Staff',
  },
  {
    id: 'REQ003',
    citizen_id: 'CIT003',
    type: 'street_repair',
    status: 'approved',
    submission_date: '2024-01-10',
    completion_date: '2024-01-18',
    description: 'Pothole on Main Street needs repair',
    citizenName: 'Michael Brown',
  },
];

export const mockPermits: Permit[] = [
  {
    id: 'PER001',
    type: 'business',
    applicant_id: 'CIT004',
    status: 'approved',
    issue_date: '2024-01-05',
    expiry_date: '2025-01-05',
    related_documents: ['business_plan.pdf', 'tax_id.pdf'],
    citizenName: 'Emily Davis',
    description: 'Restaurant business license',
    fee: 500,
  },
  {
    id: 'PER002',
    type: 'construction',
    applicant_id: 'CIT005',
    status: 'in_review',
    issue_date: '2024-01-12',
    related_documents: ['blueprints.pdf', 'land_deed.pdf'],
    citizenName: 'Robert Wilson',
    description: 'Residential building permit',
    fee: 2000,
  },
];

export const mockPayments: Payment[] = [
  {
    id: 'PAY001',
    citizen_id: 'CIT001',
    amount: 1200,
    payment_type: 'property_tax',
    date: '2024-02-01',
    status: 'pending',
    citizenName: 'John Smith',
  },
  {
    id: 'PAY002',
    citizen_id: 'CIT002',
    amount: 85,
    payment_type: 'water',
    date: '2024-01-25',
    status: 'paid',
    citizenName: 'Sarah Johnson',
    receiptNumber: 'REC2024001',
  },
  {
    id: 'PAY003',
    citizen_id: 'CIT003',
    amount: 150,
    payment_type: 'electricity',
    date: '2024-01-15',
    status: 'overdue',
    citizenName: 'Michael Brown',
  },
];

export const mockProjects: Project[] = [
  {
    id: 'PRJ001',
    name: 'City Park Renovation',
    department_id: 'DEPT001',
    budget: 500000,
    start_date: '2023-09-01',
    end_date: '2024-06-30',
    status: 'in_progress',
    description: 'Complete renovation of central city park including new playground and walking paths',
    spent: 325000,
    manager: 'Project Manager',
    progress: 65,
  },
  {
    id: 'PRJ002',
    name: 'Road Infrastructure Upgrade',
    department_id: 'DEPT002',
    budget: 1200000,
    start_date: '2024-03-01',
    end_date: '2024-12-31',
    status: 'planning',
    description: 'Upgrade main roads and install new traffic lights',
    spent: 50000,
    manager: 'Project Manager',
    progress: 5,
  },
  {
    id: 'PRJ003',
    name: 'Community Center Construction',
    department_id: 'DEPT003',
    budget: 850000,
    start_date: '2023-11-01',
    end_date: '2024-08-31',
    status: 'in_progress',
    description: 'Build new community center with sports facilities',
    spent: 420000,
    manager: 'Project Manager',
    progress: 50,
  },
];

export const mockTasks: Task[] = [
  {
    id: 'TSK001',
    project_id: 'PRJ001',
    title: 'Install new playground equipment',
    assignee_id: 'EMP001',
    status: 'in_progress',
    start_date: '2024-02-01',
    end_date: '2024-02-15',
    description: 'Setup swings, slides, and climbing structures',
    assigneeName: 'Team A',
    priority: 'high',
  },
  {
    id: 'TSK002',
    project_id: 'PRJ001',
    title: 'Landscape garden areas',
    assignee_id: 'EMP002',
    status: 'todo',
    start_date: '2024-02-16',
    end_date: '2024-03-01',
    description: 'Plant trees and flowers in designated zones',
    assigneeName: 'Team B',
    priority: 'medium',
  },
];

export const mockEmployees: Employee[] = [
  {
    id: 'EMP001',
    user_id: 'USR001',
    position: 'System Administrator',
    department_id: 'DEPT001',
    hire_date: '2020-01-15',
    salary: 75000,
    name: 'Admin User',
    email: 'admin@mms.gov',
    phone: '+1-555-0101',
    departmentName: 'Administration',
    status: 'active',
  },
  {
    id: 'EMP002',
    user_id: 'USR002',
    position: 'Senior Finance Officer',
    department_id: 'DEPT002',
    hire_date: '2019-03-20',
    salary: 65000,
    name: 'Finance Officer',
    email: 'finance@mms.gov',
    phone: '+1-555-0102',
    departmentName: 'Finance',
    status: 'active',
  },
  {
    id: 'EMP003',
    user_id: 'USR003',
    position: 'Project Manager',
    department_id: 'DEPT003',
    hire_date: '2021-06-10',
    salary: 70000,
    name: 'Project Manager',
    email: 'project@mms.gov',
    phone: '+1-555-0103',
    departmentName: 'Urban Planning',
    status: 'active',
  },
  {
    id: 'EMP004',
    user_id: 'USR004',
    position: 'HR Manager',
    department_id: 'DEPT004',
    hire_date: '2020-08-25',
    salary: 68000,
    name: 'HR Manager',
    email: 'hr@mms.gov',
    phone: '+1-555-0104',
    departmentName: 'Human Resources',
    status: 'active',
  },
];

export const mockAttendance: Attendance[] = [
  {
    id: 'ATT001',
    employee_id: 'EMP001',
    date: '2024-01-22',
    check_in: '08:30',
    check_out: '17:00',
    hours_worked: 8.5,
    employeeName: 'Admin User',
    status: 'present',
  },
  {
    id: 'ATT002',
    employee_id: 'EMP002',
    date: '2024-01-22',
    check_in: '09:15',
    check_out: '17:30',
    hours_worked: 8.25,
    employeeName: 'Finance Officer',
    status: 'late',
  },
];

export const mockLeaves: Leave[] = [
  {
    id: 'LEV001',
    employee_id: 'EMP003',
    type: 'vacation',
    start_date: '2024-02-05',
    end_date: '2024-02-09',
    reason: 'Family vacation',
    status: 'approved',
    days: 5,
    employeeName: 'Project Manager',
  },
  {
    id: 'LEV002',
    employee_id: 'EMP004',
    type: 'sick',
    start_date: '2024-01-23',
    end_date: '2024-01-24',
    reason: 'Medical appointment',
    status: 'pending',
    days: 2,
    employeeName: 'HR Manager',
  },
];

export const mockEvents: Event[] = [
  {
    id: 'EVT001',
    title: 'Town Hall Meeting',
    description: 'Monthly town hall meeting with citizens',
    date: '2024-02-10',
    location: 'City Hall Auditorium',
    organizer: 'Mayor Office',
    capacity: 200,
    registered: 145,
    type: 'official',
    status: 'upcoming',
  },
  {
    id: 'EVT002',
    title: 'Summer Festival',
    description: 'Annual summer cultural festival',
    date: '2024-07-15',
    location: 'Central Park',
    organizer: 'Cultural Department',
    capacity: 5000,
    registered: 1200,
    type: 'cultural',
    status: 'upcoming',
  },
  {
    id: 'EVT003',
    title: 'Community Sports Day',
    description: 'Sports activities for all ages',
    date: '2024-03-20',
    location: 'Sports Complex',
    organizer: 'Sports Department',
    capacity: 1000,
    registered: 650,
    type: 'sports',
    status: 'upcoming',
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'NOT001',
    userId: '6',
    title: 'Request Approved',
    message: 'Your residency certificate request has been approved',
    type: 'success',
    read: false,
    timestamp: '2024-01-22T10:30:00',
    link: '/citizen/requests',
  },
  {
    id: 'NOT002',
    userId: '6',
    title: 'Payment Due',
    message: 'Property tax payment is due in 10 days',
    type: 'warning',
    read: false,
    timestamp: '2024-01-22T09:15:00',
    link: '/citizen/finance',
  },
  {
    id: 'NOT003',
    userId: '6',
    title: 'New Event',
    message: 'Town Hall Meeting scheduled for Feb 10',
    type: 'info',
    read: true,
    timestamp: '2024-01-21T14:20:00',
    link: '/events',
  },
];
